---
title: "DistributionCompare"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r dataManipulation, echo=FALSE, fig.width=6, fig.height=4, echo=FALSE, message=FALSE, warning=FALSE, dev='pdf'}
#load libraries
library(ggplot2)
library(reshape2)
library(plyr)

#load data from file
distData <- read.table("/Users/dennisg/Documents/Manuscripts/FragmentIsotopicDistribution/data/HT/distributionScores.out", header=T, sep="\t")
#only distributions flagged as valid
distData <- distData[which(distData$distributionValid == 1), ]

#Chi-squared file headers
X2headers <- c("exactPrecursorX2","exactCondFragmentX2","approxPrecursorFromWeightX2","approxFragmentFromWeightX2","approxFragmentFromWeightAndSX2")
#Manhattan distance file headers
VDheaders <- c("exactPrecursorVD","exactCondFragmentVD","approxPrecursorFromWeightVD","approxFragmentFromWeightVD","approxFragmentFromWeightAndSVD")
#PearsonsCC file headers
CCheaders <- c("exactPrecursorCC","exactCondFragmentCC","approxPrecursorFromWeightCC","approxFragmentFromWeightCC","approxFragmentFromWeightAndSCC")
#Chi-squared normalized file headers
X2headersNorm <- c("exactPrecursorX2_norm","exactCondFragmentX2_norm","approxPrecursorFromWeightX2_norm","approxFragmentFromWeightX2_norm","approxFragmentFromWeightAndSX2_norm")
#Manhattan distance normalized file headers
VDheadersNorm <- c("exactPrecursorVD_norm","exactCondFragmentVD_norm","approxPrecursorFromWeightVD_norm","approxFragmentFromWeightVD_norm","approxFragmentFromWeightAndSVD_norm")
#PearsonsCC normalized file headers
CCheadersNorm <- c("exactPrecursorCC_norm","exactCondFragmentCC_norm","approxPrecursorFromWeightCC_norm","approxFragmentFromWeightCC_norm","approxFragmentFromWeightAndSCC_norm")


#loop through each search depth
for (searchDepth in 2:5) {
  #truncate to distributions at search depth
  distAtDepth <- distData[which(distData$completeAtDepth == searchDepth),]
  #truncate to distributions at search depth but have complete distributions
  distAtDepthComplete <- distAtDepth[which(distAtDepth$completeFlag == 1),]
  
  #melt for chi squared data
  meltedX2_AtDepth <- melt(distAtDepth, id.vars="ionID", measure.vars=X2headers)
  meltedX2_Complete <- melt(distAtDepthComplete, id.vars="ionID", measure.vars=X2headers)
  meltedX2_AtDepth_Norm <- melt(distAtDepth, id.vars="ionID", measure.vars=X2headersNorm)
  meltedX2_Complete_Norm <- melt(distAtDepthComplete, id.vars="ionID", measure.vars=X2headersNorm)
  #melt for manhattan distance data
  meltedVD_AtDepth <- melt(distAtDepth, id.vars="ionID", measure.vars=VDheaders)
  meltedVD_Complete <- melt(distAtDepthComplete, id.vars="ionID", measure.vars=VDheaders)
  meltedVD_AtDepth_Norm <- melt(distAtDepth, id.vars="ionID", measure.vars=VDheadersNorm)
  meltedVD_Complete_Norm <- melt(distAtDepthComplete, id.vars="ionID", measure.vars=VDheadersNorm)
  #melt for PearsonCC data
  #meltedCC_AtDepth <- melt(distAtDepth, id.vars="ionID", measure.vars=CCheaders)
  #meltedCC_Complete <- melt(distAtDepthComplete, id.vars="ionID", measure.vars=CCheaders)
  #meltedCC_AtDepth_Norm <- melt(distAtDepth, id.vars="ionID", measure.vars=CCheadersNorm)
  #meltedCC_Complete_Norm <- melt(distAtDepthComplete, id.vars="ionID", measure.vars=CCheadersNorm)
  
  #rename melted factors for Chi Squared data
  meltedX2_AtDepth$variable <- as.character(meltedX2_AtDepth$variable)
  meltedX2_Complete$variable <- as.character(meltedX2_Complete$variable)
  meltedX2_AtDepth_Norm$variable <- as.character(meltedX2_AtDepth_Norm$variable)
  meltedX2_Complete_Norm$variable <- as.character(meltedX2_Complete_Norm$variable)
  meltedX2_AtDepth$variable[meltedX2_AtDepth$variable == "exactPrecursorX2"] <- "ExactPrecursor"
  meltedX2_Complete$variable[meltedX2_Complete$variable == "exactPrecursorX2"] <- "ExactPrecursor"
  meltedX2_AtDepth_Norm$variable[meltedX2_AtDepth_Norm$variable == "exactPrecursorX2_norm"] <- "ExactPrecursor"
  meltedX2_Complete_Norm$variable[meltedX2_Complete_Norm$variable == "exactPrecursorX2_norm"] <- "ExactPrecursor"
  meltedX2_AtDepth$variable[meltedX2_AtDepth$variable == "exactCondFragmentX2"] <- "ExactFragment"
  meltedX2_Complete$variable[meltedX2_Complete$variable == "exactCondFragmentX2"] <- "ExactFragment"
  meltedX2_AtDepth_Norm$variable[meltedX2_AtDepth_Norm$variable == "exactCondFragmentX2_norm"] <- "ExactFragment"
  meltedX2_Complete_Norm$variable[meltedX2_Complete_Norm$variable == "exactCondFragmentX2_norm"] <- "ExactFragment"
  meltedX2_AtDepth$variable[meltedX2_AtDepth$variable == "approxPrecursorFromWeightX2"] <- "ApproxPrecursor"
  meltedX2_Complete$variable[meltedX2_Complete$variable == "approxPrecursorFromWeightX2"] <- "ApproxPrecursor"
  meltedX2_AtDepth_Norm$variable[meltedX2_AtDepth_Norm$variable == "approxPrecursorFromWeightX2_norm"] <- "ApproxPrecursor"
  meltedX2_Complete_Norm$variable[meltedX2_Complete_Norm$variable == "approxPrecursorFromWeightX2_norm"] <- "ApproxPrecursor"
  meltedX2_AtDepth$variable[meltedX2_AtDepth$variable == "approxFragmentFromWeightX2"] <- "ApproxFragment"
  meltedX2_Complete$variable[meltedX2_Complete$variable == "approxFragmentFromWeightX2"] <- "ApproxFragment"
  meltedX2_AtDepth_Norm$variable[meltedX2_AtDepth_Norm$variable == "approxFragmentFromWeightX2_norm"] <- "ApproxFragment"
  meltedX2_Complete_Norm$variable[meltedX2_Complete_Norm$variable == "approxFragmentFromWeightX2_norm"] <- "ApproxFragment"
  meltedX2_AtDepth$variable[meltedX2_AtDepth$variable == "approxFragmentFromWeightAndSX2"] <- "ApproxFragmentSulf"
  meltedX2_Complete$variable[meltedX2_Complete$variable == "approxFragmentFromWeightAndSX2"] <- "ApproxFragmentSulf"
  meltedX2_AtDepth_Norm$variable[meltedX2_AtDepth_Norm$variable == "approxFragmentFromWeightAndSX2_norm"] <- "ApproxFragmentSulf"
  meltedX2_Complete_Norm$variable[meltedX2_Complete_Norm$variable == "approxFragmentFromWeightAndSX2_norm"] <- "ApproxFragmentSulf"
  meltedX2_AtDepth$variable <- as.factor(meltedX2_AtDepth$variable)
  meltedX2_Complete$variable <- as.factor(meltedX2_Complete$variable)
  meltedX2_AtDepth_Norm$variable <- as.factor(meltedX2_AtDepth_Norm$variable)
  meltedX2_Complete_Norm$variable <- as.factor(meltedX2_Complete_Norm$variable)
  
  #rename melted factors for manhattan distance data
  meltedVD_AtDepth$variable <- as.character(meltedVD_AtDepth$variable)
  meltedVD_Complete$variable <- as.character(meltedVD_Complete$variable)
  meltedVD_AtDepth_Norm$variable <- as.character(meltedVD_AtDepth_Norm$variable)
  meltedVD_Complete_Norm$variable <- as.character(meltedVD_Complete_Norm$variable)
  meltedVD_AtDepth$variable[meltedVD_AtDepth$variable == "exactPrecursorVD"] <- "ExactPrecursor"
  meltedVD_Complete$variable[meltedVD_Complete$variable == "exactPrecursorVD"] <- "ExactPrecursor"
  meltedVD_AtDepth_Norm$variable[meltedVD_AtDepth_Norm$variable == "exactPrecursorVD_norm"] <- "ExactPrecursor"
  meltedVD_Complete_Norm$variable[meltedVD_Complete_Norm$variable == "exactPrecursorVD_norm"] <- "ExactPrecursor"
  meltedVD_AtDepth$variable[meltedVD_AtDepth$variable == "exactCondFragmentVD"] <- "ExactFragment"
  meltedVD_Complete$variable[meltedVD_Complete$variable == "exactCondFragmentVD"] <- "ExactFragment"
  meltedVD_AtDepth_Norm$variable[meltedVD_AtDepth_Norm$variable == "exactCondFragmentVD_norm"] <- "ExactFragment"
  meltedVD_Complete_Norm$variable[meltedVD_Complete_Norm$variable == "exactCondFragmentVD_norm"] <- "ExactFragment"
  meltedVD_AtDepth$variable[meltedVD_AtDepth$variable == "approxPrecursorFromWeightVD"] <- "ApproxPrecursor"
  meltedVD_Complete$variable[meltedVD_Complete$variable == "approxPrecursorFromWeightVD"] <- "ApproxPrecursor"
  meltedVD_AtDepth_Norm$variable[meltedVD_AtDepth_Norm$variable == "approxPrecursorFromWeightVD_norm"] <- "ApproxPrecursor"
  meltedVD_Complete_Norm$variable[meltedVD_Complete_Norm$variable == "approxPrecursorFromWeightVD_norm"] <- "ApproxPrecursor"
  meltedVD_AtDepth$variable[meltedVD_AtDepth$variable == "approxFragmentFromWeightVD"] <- "ApproxFragment"
  meltedVD_Complete$variable[meltedVD_Complete$variable == "approxFragmentFromWeightVD"] <- "ApproxFragment"
  meltedVD_AtDepth_Norm$variable[meltedVD_AtDepth_Norm$variable == "approxFragmentFromWeightVD_norm"] <- "ApproxFragment"
  meltedVD_Complete_Norm$variable[meltedVD_Complete_Norm$variable == "approxFragmentFromWeightVD_norm"] <- "ApproxFragment"
  meltedVD_AtDepth$variable[meltedVD_AtDepth$variable == "approxFragmentFromWeightAndSVD"] <- "ApproxFragmentSulf"
  meltedVD_Complete$variable[meltedVD_Complete$variable == "approxFragmentFromWeightAndSVD"] <- "ApproxFragmentSulf"
  meltedVD_AtDepth_Norm$variable[meltedVD_AtDepth_Norm$variable == "approxFragmentFromWeightAndSVD_norm"] <- "ApproxFragmentSulf"
  meltedVD_Complete_Norm$variable[meltedVD_Complete_Norm$variable == "approxFragmentFromWeightAndSVD_norm"] <- "ApproxFragmentSulf"
  meltedVD_AtDepth$variable <- as.factor(meltedVD_AtDepth$variable)
  meltedVD_Complete$variable <- as.factor(meltedVD_Complete$variable)
  meltedVD_AtDepth_Norm$variable <- as.factor(meltedVD_AtDepth_Norm$variable)
  meltedVD_Complete_Norm$variable <- as.factor(meltedVD_Complete_Norm$variable)
  
  #plot chi squared density
  plotX2_atDepth <- ggplot(data = meltedX2_AtDepth, mapping = aes(x=value, color=variable)) +
    geom_density() +
    scale_x_log10() +
    theme(legend.position = "right",
          legend.text = element_text(size = 10),
          axis.title = element_text(size=12),
          plot.title = element_text(size=16)) +
    ggtitle(paste("Chi-Squared at Depth: ", searchDepth, sep = "")) +
    ylab("Density") +
    xlab(expression(X^{2}))
  
  #plot manhattan distance
  plotVD_atDepth <- ggplot(data = meltedVD_AtDepth, mapping = aes(x=value, color=variable)) +
    geom_density() +
    theme(legend.position = "right",
          legend.text = element_text(size = 10),
          axis.title = element_text(size=12),
          plot.title = element_text(size=16)) +
    ggtitle(paste("Manhattan Distance at Depth: ", searchDepth, sep = "")) +
    ylab("Density") +
    xlab("Total Variation")
  
  #plot chi squared density
  plotX2_Complete <- ggplot(data = meltedX2_Complete, mapping = aes(x=value, color=variable)) +
    geom_density() +
    scale_x_log10() +
    theme(legend.position = "right",
          legend.text = element_text(size = 10),
          axis.title = element_text(size=12),
          plot.title = element_text(size=16)) +
    ggtitle(paste("Chi-Squared Complete at Depth: ", searchDepth, sep = "")) +
    ylab("Density") +
    xlab(expression(X^{2}))
  
  #plot manhattan distance
  plotVD_Complete <- ggplot(data = meltedVD_Complete, mapping = aes(x=value, color=variable)) +
    geom_density() +
    theme(legend.position = "right",
          legend.text = element_text(size = 10),
          axis.title = element_text(size=12),
          plot.title = element_text(size=16)) +
    ggtitle(paste("Manhattan Dist. Complete at Depth: ", searchDepth, sep = "")) +
    ylab("Density") +
    xlab("Total Variation")
  
  #plot chi squared density
  plotX2_atDepth_Norm <- ggplot(data = meltedX2_AtDepth_Norm, mapping = aes(x=value, color=variable)) +
    geom_density() +
    scale_x_log10() +
    theme(legend.position = "right",
          legend.text = element_text(size = 10),
          axis.title = element_text(size=12),
          plot.title = element_text(size=16)) +
    ggtitle(paste("Chi-Squared Norm. at Depth: ", searchDepth, sep = "")) +
    ylab("Density") +
    xlab(expression(X^{2}))
  
  #plot manhattan distance
  plotVD_atDepth_Norm <- ggplot(data = meltedVD_AtDepth_Norm, mapping = aes(x=value, color=variable)) +
    geom_density() +
    theme(legend.position = "right",
          legend.text = element_text(size = 10),
          axis.title = element_text(size=12),
          plot.title = element_text(size=16)) +
    ggtitle(paste("Manhattan Dist. Norm. at Depth: ", searchDepth, sep = "")) +
    ylab("Density") +
    xlab("Total Variation")
  
  #plot chi squared density
  plotX2_Complete_Norm <- ggplot(data = meltedX2_Complete_Norm, mapping = aes(x=value, color=variable)) +
    geom_density() +
    scale_x_log10() +
    theme(legend.position = "right",
          legend.text = element_text(size = 10),
          axis.title = element_text(size=12),
          plot.title = element_text(size=16)) +
    ggtitle(paste("Chi-Squared Norm. Complete at Depth: ", searchDepth, sep = "")) +
    ylab("Density") +
    xlab(expression(X^{2}))
  
  #plot manhattan distance
  plotVD_Complete_Norm <- ggplot(data = meltedVD_Complete_Norm, mapping = aes(x=value, color=variable)) +
    geom_density() +
    theme(legend.position = "right",
          legend.text = element_text(size = 10),
          axis.title = element_text(size=12),
          plot.title = element_text(size=16)) +
    ggtitle(paste("Manhattan Dist. Norm. Complete at Depth: ", searchDepth, sep = "")) +
    ylab("Density") +
    xlab("Total Variation")
  
  print(plotX2_atDepth)
  print(ddply(meltedX2_AtDepth, "variable", summarize, mean=mean(value), min=min(value), max=max(value), sd=sd(value), count=length(value)))
  print(plotVD_atDepth)
  print(ddply(meltedVD_AtDepth, "variable", summarize, mean=mean(value), min=min(value), max=max(value), sd=sd(value), count=length(value)))
  print(plotX2_Complete)
  print(ddply(meltedX2_Complete, "variable", summarize, mean=mean(value), min=min(value), max=max(value), sd=sd(value), count=length(value)))
  print(plotVD_Complete)
  print(ddply(meltedVD_Complete, "variable", summarize, mean=mean(value), min=min(value), max=max(value), sd=sd(value), count=length(value)))
  print(plotX2_atDepth_Norm)
  print(ddply(meltedX2_AtDepth_Norm, "variable", summarize, mean=mean(value), min=min(value), max=max(value), sd=sd(value), count=length(value)))
  print(plotVD_atDepth_Norm)
  print(ddply(meltedVD_AtDepth_Norm, "variable", summarize, mean=mean(value), min=min(value), max=max(value), sd=sd(value), count=length(value)))
  print(plotX2_Complete_Norm)
  print(ddply(meltedX2_Complete_Norm, "variable", summarize, mean=mean(value), min=min(value), max=max(value), sd=sd(value), count=length(value)))
  print(plotVD_Complete_Norm)
  print(ddply(meltedVD_Complete_Norm, "variable", summarize, mean=mean(value), min=min(value), max=max(value), sd=sd(value), count=length(value)))
}

```